[grpc]
address = ["unix:///run/buildkit/buildkitd.sock"]
socketMode = "0666"

[worker.oci]
enabled = true
snapshotter = "overlayfs"
max-parallelism = 8

[registry."registry:5000"]
http = true
insecure = true
